const constants = {
    reducerActions: {
        ADD_CONNECTION: "ADD_CONNECTION",
        REMOVE_CONNECTION: "REMOVE_CONNECTION",
        TOGGLE_ADD_CONNECTION_DIALOG: "TOGGLE_ADD_CONNECTION_DIALOG",
        SET_ACTIVE_CONNECTION: "SET_ACTIVE_CONNECTION"
    }
}

export default constants;