const constants = {
  reducerActions: {
    CREATE_NEW_TAB: "CREATE_NEW_TAB",
    REMOVE_TAB: "REMOVE_TAB",
    SET_CURRENT_TAB_DATA: "SET_CURRENT_TAB_DATA",
    SET_SELECTED_TAB: "SET_SELECTED_TAB",
    OPEN_WORKSPACE: "OPEN_WORKSPACE",
    CLOSE_WORKSPACE: "CLOSE_WORKSPACE",
  },
};

export default constants;
